main/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('accounts/signup/', views.signup, name='signup'),
  path('nfts/create/', views.NFTCreate.as_view(), name='nft_create'),
  path('nfts/<int:nft_id>/', views.nft_detail, name='detail'),
  path('nfts/', views.nft_index, name='nft_index'),
  path('nfts/all/', views.NFTList.as_view(), name='nft_list'),
  path('nfts/<int:pk>/edit/', views.NFTEdit.as_view(), name='nft_edit'),
  path('nfts/<int:nft_id>/add_photo/', views.add_photo, name='add_photo'),
  path('nfts/<int:pk>/delete/', views.NFTDelete.as_view(), name='nft_delete'),
  path('nfts/<int:nft_id>/add_bid/', views.add_bid, name='add_bid'),
  path('nfts/search_result/', views.search_result, name='search_result'),
  path('nfts/<int:nft_id>/add_sell/', views.sell, name='sell'),
  path('nfts/for_sale', views.all_for_sale, name='for_sale'),
  path('like/<int:pk>', views.likeview, name='like_nft'),
]

nftmarket/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import random
import datetime


def random_token():
    return int(random.randint(10000, 99999))
    
class NFT(models.Model):
    id = models.AutoField(primary_key=True)
    nft_name = models.CharField(("NFT Name"),max_length=50)
    token_id = models.IntegerField(default=random_token)
    blockchain = models.CharField(max_length=10)
    description = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.nft_name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'nft_id': self.id})

class Bid(models.Model):
  date = models.DateField(("Date"), default=datetime.date.today)
  bidprice = models.FloatField(("Bid Price"))
  nft = models.ForeignKey(NFT, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_bidprice_display()} on {self.date}"
    
  class Meta:
    ordering = ('-bidprice',)

class Sell(models.Model):
  sale_ends = models.DateField(("Date Sale Ends"))
  minbidprice = models.FloatField(("Minimum Bid Price (in ETH)"))
  nft = models.ForeignKey(NFT, on_delete=models.CASCADE)

class Photo(models.Model):
    url = models.CharField(max_length=200)
    nft = models.ForeignKey(NFT, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for nft_id: {self.nft_id} @{self.url}"

main/forms.py
from django.forms import ModelForm
from .models import Bid, Sell

class BidForm(ModelForm):
  class Meta:
    model = Bid
    fields = ['bidprice']

class SellForm(ModelForm):
  class Meta:
    model = Sell
    fields = ['sale_ends','minbidprice']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from .models import NFT, Photo, Sell
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
# Import the login_required decorator
from django.contrib.auth.decorators import login_required
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from .forms import BidForm, SellForm
import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'nftmarketgallery'

@login_required
def add_photo(request, nft_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}/{BUCKET}/{key}"
            photo = Photo(url=url, nft_id=nft_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
        return redirect('detail', nft_id=nft_id)

class NFTCreate(LoginRequiredMixin, CreateView):
  model = NFT
  fields = ['nft_name','description']
  def get_success_url(self):
        return reverse('detail', kwargs={'nft_id': self.object.id})
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class NFTEdit(LoginRequiredMixin, UpdateView):
  model = NFT
  fields = ['nft_name', 'description']
  def get_success_url(self):
    return reverse('detail', kwargs={'nft_id': self.object.id})
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class NFTDelete(LoginRequiredMixin, DeleteView):
  model = NFT
  success_url='/nfts/'

class NFTList(ListView):
  model = NFT

@login_required
def add_bid(request, nft_id):
  form = BidForm(request.POST)
  if form.is_valid():
    new_bid = form.save(commit=False)
    new_bid.nft_id = nft_id
    new_bid.save()
  return redirect('detail', nft_id=nft_id)


@login_required
def nft_detail(request, nft_id):
  nft = NFT.objects.get(id=nft_id)
  bid_form = BidForm()
  return render(request, 'nfts/detail.html', { 'nft': nft, 'bid_form':bid_form})
  template_name = 'detail.html'

def get_context_data(self, *args, **kwargs):
    stuff = get_object_or_404(NFT, id=self.kwargs['pk'])
    total_likes = stuff.total_likes()
    context["total_likes"] = total_likes
    return context

def likeview(request, pk):

  nft = get_object_or_404(NFT, pk=pk)
  nft.likes.add(request.user)
  return HttpResponseRedirect(reverse('detail', args=[str(pk)]))

@login_required
def nft_index(request):
  nfts = NFT.objects.filter(user=request.user)
  # nfts = NFT.objects.all()
  return render(request, 'nfts/index.html', { 'nfts': nfts }) 

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def home(request):
  return render(request, 'home.html')

def search_result(request):
  if request.method == "GET":
    searched = request.GET['searched']
    search_result = NFT.objects.filter(nft_name__contains=searched)
    return render(request, 'main/nft_search_result.html', {'searched': searched, 'search_result':search_result})
  else:
    return render(request, 'main/nft_search_result.html')

@login_required
def sell(request, nft_id):
  form = SellForm(request.POST)
  if form.is_valid():
    new_sell = form.save(commit=False)
    new_sell.nft_id = nft_id
    new_sell.save()
    return redirect('detail', nft_id=nft_id)
  return render(request, 'main/sell_form.html', { 'nft': nft_id,'form':form})

def all_for_sale(request):
  nft = NFT.objects.all()
  return render(request, 'nfts/for_sale.html',{ 'nft': nft }) 
  

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NFT Gallery</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Caladea&family=Hind+Siliguri&family=Roboto+Mono:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
</head>

<body>
    
    <header class="navbar-fixed">
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <ul class="nav-menu">
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;NFT GALLERY</a></li>
                </ul>
                <a href="#"></a>
                <ul id="nav-mobile" class="right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">LOG OUT</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">SIGN UP</a></li>
                    <li><a href="{% url 'login' %}">LOG IN</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="container-fixed">
                <ul class="left">
                    <li class="search">
                        <form action="{% url 'search_result' %}" method="get">
                            <input id = searchbar type="search" placeholder="Search NFTs" name='searched'>
                            <button id="search" class="material-icons white-text" type="submit">search</button>
                        </form>
                    </li>
            </div>
                <ul class="left">
                    <li><a href="{% url 'nft_list' %}">EXPLORE</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'for_sale' %}">NFT'S FOR SALE</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'nft_index' %}">{{user |upper}}'S NFT'S</a></li>
                    <li><a href="{% url 'nft_create' %}">CREATE</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <div class="container-fixed">
        <ul class="right">
            <li class="search">
                <form action="{% url 'search_result' %}" method="get">
                    <input id = searchbar type="search" placeholder="Search NFTs" name='searched'>
                    <button id="search" class="material-icons white-text" type="submit">search</button>
                </form>
            </li>
    </div>
    <main class="container">
        {% block content %} {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2022 NFT Marketplace &nbsp;</div>
    </footer>
    <script>

        $(document).ready(function(){
            $('.collapsible').collapsible();
          });
        
        </script>
</body>

</html>

main/templates/home.html
{% extends 'base.html' %} {% block content %} 

<h1>DISCOVER EXTRAORDINARY NFT'S</h1>
<h2 class="header-text">An NFT Gallery application created by a team of 4 General Assembly students</h2>

<div class="classone">
    <a href="https://www.linkedin.com/in/marianne-salamanca-badilla/" target='blank'>
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Marianne</h2>
                <p><small>SEI-44</small></p>
            </div>
        </div>
    </a>
    <a href="https://www.linkedin.com/in/tatsiana-prokharchyk-614262147/" target='blank'>
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Tatsiana</h2>
                <p><small>SEI-44</small></p>
            </div>
        </div>
    </a>
</div>

<div class="classtwo">
    <a href="https://www.linkedin.com/in/tiffany-lam-8b101724/" target='blank'>
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Tiffany</h2>
                <p><small>SEI-44</small></p>
            </div>
        </div>
    </a>
    <a href="https://www.linkedin.com/in/anthony-vanoni/" target='blank'>
        <div class="card">
            <div class="card-content">
                <h2 class="card-title">Anthony</h2>
                <p><small>SEI-44</small></p>
            </div>
        </div>
    </a>
</div>
{% endblock %}

main/templates/main/nft_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>DELETE NFT</h1>

  <h4 class="header-text">Are you sure you want to delete <span class="teal-text">'{{ nft.nft_name }}'</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' nft.id %}">Cancel</a>
  </form>
{% endblock %}

main/templates/main/nft_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>EDIT <span class="teal-text">'{{nft.nft_name}}'</span></h1>
  {% else %}
    <h1>CREATE NFT</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main/templates/main/nft_list.html
{% extends 'base.html' %} {% block content %}

<h1>ALL NFT'S</h1>

{% for nft in nft_list %}
<a href="{% url 'detail' nft.id %}">
    <div class="card">
        <div class="card-content">
            <div class="card-img-container">
                {% for photo in nft.photo_set.all %}
                {% for sell in nft.sell_set.all %}
                <div class="teal-text"><h5>FOR SALE</h5></div>
                {% endfor %}
                    <img class="responsive-img card-panel" src="{{photo.url}}"> {% empty %}
                    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                {% endfor %}
            </div>
            <h2 class="card-title">{{ nft.nft_name }}</h2>
            <p><small>{{ nft.token_id }}</small></p>
        </div>
    </div>
</a>
{% endfor %} {% endblock %}

main/templates/main/nft_search_result.html
{% extends 'base.html' %}

{% block content %}
    {% if searched %}
        <h1>You searched for '{{ searched }}'</h1>
        <br/>
        {% if search_result|length %}
            {% for nft in search_result %}
                <a href="{% url 'detail' nft.id %}">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-img-container">
                                {% for photo in nft.photo_set.all %}
                                    <img class="responsive-img card-panel" src="{{photo.url}}"> {% empty %}
                                    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                                {% endfor %}
                            </div>
                            <h2 class="card-title">{{ nft.nft_name }}</h2>
                            <p><small>{{ nft.token_id }}</small></p>
                        </div>
                    </div>
                </a><br/>
            {% endfor %}
        {% else %}
            <h1 class = "nonft">No NFT's Found :(</h1> 
        {% endif %}   
    {% else %}
        <h1>Hey! You forgot to enter a NFT name in the search box.</h1>
    {% endif %}
{% endblock %}

main/templates/main/sell_form.html
{% extends 'base.html' %} {% block content %}

    <h1>SELL AN NFT</h1>
  <form action='' method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
<!-- Date Picker -->
  <script>
    var dateEl = document.getElementById('id_sale_ends');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  </script>
{% endblock %}

main/templates/nfts/detail.html
{% extends 'base.html' %} {% block content %} {%load mathfilters%}

<h1>{{nft.nft_name}}</h1>
<div class="bidcard">
    <div class="card">
        <div class="card-content">
            <span class="card-title"></span> {% for photo in nft.photo_set.all %}
            <img class="responsive-img card-panel" src="{{photo.url}}"> {% empty %}
            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
            {% if notempty %} <br> {% elif nft.user == request.user %}
            <form action="{% url 'add_photo' nft.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
                {% csrf_token %}
                <input type="file" name="photo-file">
                <br><br>
                <input type="submit" class="btn" value="Upload Photo">
            </form>
            {% endif %} {% endfor %}
            <form action="{% url 'like_nft' nft.pk %}" method="POST" class="right">
                {% csrf_token %}
                <button type="submit", name = "nft_id", value="{{ post.id}}" class="waves-effect waves-light btn-small"> Like <i class="tiny material-icons">favorite</i> </button>
                <br>
                {{nft.total_likes}} Likes
            </form>    
            <p>Creator: {{ nft.user }}</p>
            <p>Blockchain: Ethereum</p>
            <p>Token ID: {{ nft.token_id }}</p>
            <p>Description: {{ nft.description }}</p>
            {% if nft.user == request.user %}
            <a href="{% url 'nft_edit' nft.id %}" class="waves-effect waves-light btn-small">Edit</a>
            <a href="{% url 'nft_delete' nft.id %}" class="waves-effect waves-light btn-small">Delete</a> {% endif %}
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          

            <table class="striped">
              {% for bid in nft.bid_set.all %} 
              {% if forloop.first %}
            <h4>Top Bid: ETH {{ bid.bidprice }}</h4>
              {% endif %} 
            {% endfor %} 
              {% for sell in nft.sell_set.all %}
                <thead>
                    <tr>
                        <th>Sale Ends</th>
                        <th>Min Bid Price</th>
                        <th>USD</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{sell.sale_ends}}</td>
                        <td>ETH {{sell.minbidprice}}</td>
                        <td>${{sell.minbidprice|mul:2735}}</td>
                    </tr>
                    {% empty %}
                  {% if nft.user == request.user %}
                  <div class="sellbutton">
                  <h3 class = "center-align">READY TO SELL YOUR NFT?</h3>
                  <br>   
                  <div class = "center-align">
                    <a href="{% url 'sell' nft.id %}" class="waves-effect waves-light btn-large">Sell</a>                 
                  </div>
                </div>         
                  {%else%}
                    <h3 class = "center-align">SORRY! THIS NFT IS NOT FOR SALE ~_~</h3>
                  {% endif %}
                {% endfor %}
                </tbody>
            </table>

        {% for sell in nft.sell_set.all %}
            <span class="card-title"></span> 
            <hr>
            {% if nft.user == request.user %}
            <div></div>
            {%else%}
            <form action="{% url 'add_bid' nft.id %}"  class='bidprice'method="post">
                {% csrf_token %} {{ bid_form.as_p }}
                <input type="submit" class="btn" value="Add Bid">
            </form>
            {% endif %}
           
            <table class="striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Bid</th>
                        <th>USD</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bid in nft.bid_set.all %}
                    <tr>
                        <td>{{bid.date}}</td>
                        <td>ETH {{bid.bidprice}}</td>
                        <td>${{bid.bidprice|mul:2735}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endfor %} 
        </div>
    </div>
</div>
{% endblock %}

main/templates/nfts/for_sale.html
{% extends 'base.html' %} {% block content %}

<h1>NFT'S FOR SALE</h1>


{% for nft in nft %}
{% for sell in nft.sell_set.all %}
<a href="{% url 'detail' nft.id %}">
    <div class="card">
        <div class="card-content">
            <div class="card-img-container">
                {% for photo in nft.photo_set.all %}
                {% for sell in nft.sell_set.all %}
                <div class="teal-text"><h5>FOR SALE</h5></div>
                {% endfor %}
                <img class="responsive-img card-panel" src="{{photo.url}}"> {% empty %}
                <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                {% endfor %}
            </div>
            <h2 class="card-title">{{ nft.nft_name }}</h2>
            <p><small>{{ nft.token_id }}</small></p>
            <a href="{% url 'nft_edit' nft.id %}" class="waves-effect waves-light btn-small">EDIT</a>
        </div>
    </div>
</a>
{% endfor %}{% endfor %} {% endblock %}

main/templates/nfts/index.html
{% extends 'base.html' %} {% block content %}

<h1>{{user | upper}}'S NFT'S</h1>

{% for nft in nfts %}
<a href="{% url 'detail' nft.id %}">
    <div class="card">
        <div class="card-content">
            <div class="card-img-container">
                {% for photo in nft.photo_set.all %}
                {% for sell in nft.sell_set.all %}
                <div class="teal-text"><h5>FOR SALE</h5></div>
                {% endfor %}
                <img class="responsive-img card-panel" src="{{photo.url}}"> {% empty %}
                <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                {% endfor %}
            </div>
            <h2 class="card-title">{{ nft.nft_name }}</h2>
            <p><small>{{ nft.token_id }}</small></p>
            <a href="{% url 'nft_edit' nft.id %}" class="waves-effect waves-light btn-small">EDIT</a>
        </div>
    </div>
</a>
{% endfor %} {% endblock %}